### ISSUE TITLE
Dragging not possible if time+date is multiline

### ISSUE THREAD

**Issue by bithir** [unsoluble/smalltime#195]
If the date display spans over a line, the div for it spans over the dragging div in Chrome.
See discussion on Foundry Discord https://discord.com/channels/170995199584108546/722566083499786352/1189921715531304990

https://github.com/unsoluble/smalltime/assets/19734037/08250949-d400-4935-a08b-ede3ffdccf4a

**Comment by bithir** [comment]
I would suggest adding the following css elements for the dateDisplay div:
```css
element.style {
    text-overflow: ellipsis;
    text-wrap: nowrap;
}
```
